id001:
  SNR_01:
    INTF:
      - NAME: '0/0'
        VLAN: '200'
        IP: '10.10.20.4'     
      - NAME: '0/1'
        VLAN: '300'
        IP: '10.10.30.4'        
  SNR_04:
    INTF:
      - NAME: '0/0'
        VLAN: '200'
        IP: '10.10.20.5'     
      - NAME: '0/1'
        VLAN: '400'
        IP: '10.10.40.4'        
